import { Button, Grid } from "@mui/material";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Box } from "@mui/material";
import Trending from '../content/homePage/trending.json'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box sx={{ m: 0 }} className={styles.mainBg}>
        <div className={styles.mainBgOverlay}></div>
        <div className={styles.main_content}>
        <h1>Elevate your world with unique <br/> Art & Design</h1>
        <p>We believe that creativity has an immense power: to express emotions for which there are no words,</p>

<div className={styles.btn}>Get Started</div>
</div>
      </Box>

      {/* trending items */}

      <Box className={styles.trending}>
      <h1>Trending Paintings</h1>
      <p>Discover our most popular contemporary artworks for sale</p>

      <div className={styles.trendingList}>
      {Trending.map((item)=>(
        <Image width={200} height={200} src={item.url} />
      ))}
      </div>
    
      </Box>
    </>
  );
}
